// Curated emoji name table for `--emoji` (issue #55).
//
// Each entry is `(glyph, keywords)` where `keywords` is a single
// space-joined string of search terms — CLDR short name first,
// then synonyms most people would type ("good" for 👍, "fire" for
// 🔥). `SearchFilter.rank(...)` (issue #53) does the fuzzy match
// against `keywords`, so this file ONLY has to hold a useful
// vocabulary; ranking is the SearchMode pipeline's job.
//
// Coverage is intentionally curated (≈250 entries), not the full
// CLDR set (≈3700). The long tail is rarely typed by name —
// niche emoji are easier to reach via the system picker
// (Ctrl+Cmd+Space). When a user reports "I typed X and nothing
// matched", add the entry here; don't ship the full Unicode
// catalogue.
//
// Pure Core data — no AppKit, no AX. The adapter
// (`AXUIElementSource.enumerateEmoji()`) materialises these
// rows as `UIElement`s and the dispatch path
// (`AXUIElementSource.act(id:as:)`) decodes the glyph back from
// the id (`"emoji:<glyph>"`). No live AXUIElement is needed —
// dispatch synthesises a CGEvent with the glyph as a Unicode
// payload, so perch never touches the pasteboard.

import Foundation

public enum EmojiTable {

    /// One picker entry: the glyph that gets typed + the keywords
    /// that match it during fuzzy search.
    public struct Entry: Sendable, Equatable {
        public let glyph: String
        public let keywords: String
        public init(glyph: String, keywords: String) {
            self.glyph = glyph
            self.keywords = keywords
        }
    }

    /// Curated picker table. Order is "common-first" so the idle
    /// list (no query typed) surfaces high-frequency emoji.
    public static let entries: [Entry] = [
        // Faces — positive
        .init(glyph: "😀", keywords: "grinning face happy smile"),
        .init(glyph: "😃", keywords: "grinning face with big eyes happy smile"),
        .init(glyph: "😄", keywords: "grinning face with smiling eyes happy"),
        .init(glyph: "😁", keywords: "beaming face with smiling eyes happy grin"),
        .init(glyph: "😆", keywords: "grinning squinting face laugh"),
        .init(glyph: "😅", keywords: "grinning face with sweat nervous"),
        .init(glyph: "🤣", keywords: "rolling on the floor laughing rofl lol"),
        .init(glyph: "😂", keywords: "face with tears of joy lol laugh cry"),
        .init(glyph: "🙂", keywords: "slightly smiling face"),
        .init(glyph: "🙃", keywords: "upside-down face"),
        .init(glyph: "😉", keywords: "winking face wink"),
        .init(glyph: "😊", keywords: "smiling face with smiling eyes blush"),
        .init(glyph: "😇", keywords: "smiling face with halo angel innocent"),
        .init(glyph: "🥰", keywords: "smiling face with hearts love"),
        .init(glyph: "😍", keywords: "smiling face with heart-eyes love"),
        .init(glyph: "🤩", keywords: "star-struck excited amazing"),
        .init(glyph: "😘", keywords: "face blowing a kiss kiss"),
        .init(glyph: "😗", keywords: "kissing face"),
        .init(glyph: "☺️", keywords: "smiling face relaxed"),
        .init(glyph: "😚", keywords: "kissing face with closed eyes"),
        .init(glyph: "😙", keywords: "kissing face with smiling eyes"),
        .init(glyph: "🥲", keywords: "smiling face with tear bittersweet"),
        .init(glyph: "😋", keywords: "face savoring food yum delicious"),
        .init(glyph: "😛", keywords: "face with tongue tongue out"),
        .init(glyph: "😜", keywords: "winking face with tongue silly"),
        .init(glyph: "🤪", keywords: "zany face crazy silly"),
        .init(glyph: "😝", keywords: "squinting face with tongue"),
        .init(glyph: "🤑", keywords: "money-mouth face rich"),
        .init(glyph: "🤗", keywords: "smiling face with open hands hug"),
        .init(glyph: "🤭", keywords: "face with hand over mouth oops"),
        .init(glyph: "🤫", keywords: "shushing face quiet silence"),
        .init(glyph: "🤔", keywords: "thinking face hmm wonder"),
        .init(glyph: "🫡", keywords: "saluting face salute"),

        // Faces — neutral
        .init(glyph: "🤐", keywords: "zipper-mouth face quiet"),
        .init(glyph: "🤨", keywords: "face with raised eyebrow suspicious"),
        .init(glyph: "😐", keywords: "neutral face meh"),
        .init(glyph: "😑", keywords: "expressionless face"),
        .init(glyph: "😶", keywords: "face without mouth silent speechless"),
        .init(glyph: "😏", keywords: "smirking face smirk"),
        .init(glyph: "😒", keywords: "unamused face annoyed meh"),
        .init(glyph: "🙄", keywords: "face with rolling eyes annoyed"),
        .init(glyph: "😬", keywords: "grimacing face awkward"),
        .init(glyph: "🤥", keywords: "lying face liar pinocchio"),
        .init(glyph: "😌", keywords: "relieved face calm"),
        .init(glyph: "😔", keywords: "pensive face sad"),
        .init(glyph: "😪", keywords: "sleepy face tired"),
        .init(glyph: "😴", keywords: "sleeping face zzz"),
        .init(glyph: "😷", keywords: "face with medical mask sick"),

        // Faces — negative
        .init(glyph: "🤒", keywords: "face with thermometer sick fever"),
        .init(glyph: "🤕", keywords: "face with head-bandage hurt"),
        .init(glyph: "🤢", keywords: "nauseated face sick"),
        .init(glyph: "🤮", keywords: "face vomiting sick"),
        .init(glyph: "🤧", keywords: "sneezing face cold"),
        .init(glyph: "🥵", keywords: "hot face heat sweat"),
        .init(glyph: "🥶", keywords: "cold face freezing"),
        .init(glyph: "🥴", keywords: "woozy face drunk dizzy"),
        .init(glyph: "😵", keywords: "knocked-out face dizzy"),
        .init(glyph: "🤯", keywords: "exploding head mind blown shocked"),
        .init(glyph: "🤠", keywords: "cowboy hat face"),
        .init(glyph: "🥳", keywords: "partying face celebrate party"),
        .init(glyph: "🥸", keywords: "disguised face"),
        .init(glyph: "😎", keywords: "smiling face with sunglasses cool"),
        .init(glyph: "🤓", keywords: "nerd face nerd"),
        .init(glyph: "🧐", keywords: "face with monocle examine fancy"),
        .init(glyph: "😕", keywords: "confused face"),
        .init(glyph: "😟", keywords: "worried face concern"),
        .init(glyph: "🙁", keywords: "slightly frowning face sad"),
        .init(glyph: "☹️", keywords: "frowning face sad"),
        .init(glyph: "😮", keywords: "face with open mouth surprised wow"),
        .init(glyph: "😯", keywords: "hushed face"),
        .init(glyph: "😲", keywords: "astonished face shocked"),
        .init(glyph: "😳", keywords: "flushed face embarrassed"),
        .init(glyph: "🥺", keywords: "pleading face begging"),
        .init(glyph: "🥹", keywords: "face holding back tears proud touched"),
        .init(glyph: "😨", keywords: "fearful face scared"),
        .init(glyph: "😰", keywords: "anxious face with sweat nervous"),
        .init(glyph: "😥", keywords: "sad but relieved face"),
        .init(glyph: "😢", keywords: "crying face sad cry tear"),
        .init(glyph: "😭", keywords: "loudly crying face sob bawl cry"),
        .init(glyph: "😱", keywords: "face screaming in fear scared shocked"),
        .init(glyph: "😖", keywords: "confounded face frustrated"),
        .init(glyph: "😣", keywords: "persevering face struggling"),
        .init(glyph: "😞", keywords: "disappointed face sad"),
        .init(glyph: "😓", keywords: "downcast face with sweat"),
        .init(glyph: "😩", keywords: "weary face tired"),
        .init(glyph: "😫", keywords: "tired face exhausted"),
        .init(glyph: "🥱", keywords: "yawning face tired bored"),
        .init(glyph: "😤", keywords: "face with steam from nose triumph determined"),
        .init(glyph: "😡", keywords: "enraged pouting face angry mad rage"),
        .init(glyph: "😠", keywords: "angry face mad"),
        .init(glyph: "🤬", keywords: "face with symbols on mouth swear cursing"),
        .init(glyph: "😈", keywords: "smiling face with horns devil mischief"),
        .init(glyph: "👿", keywords: "angry face with horns imp devil"),
        .init(glyph: "💀", keywords: "skull dead death"),
        .init(glyph: "☠️", keywords: "skull and crossbones poison danger"),
        .init(glyph: "💩", keywords: "pile of poo shit crap"),
        .init(glyph: "🤡", keywords: "clown face creepy"),
        .init(glyph: "👻", keywords: "ghost halloween boo"),
        .init(glyph: "👽", keywords: "alien ufo"),
        .init(glyph: "👾", keywords: "alien monster space invader"),
        .init(glyph: "🤖", keywords: "robot bot"),

        // Hands & gestures
        .init(glyph: "👋", keywords: "waving hand wave hi hello bye"),
        .init(glyph: "🤚", keywords: "raised back of hand"),
        .init(glyph: "✋", keywords: "raised hand stop high five"),
        .init(glyph: "🖖", keywords: "vulcan salute spock"),
        .init(glyph: "👌", keywords: "ok hand perfect"),
        .init(glyph: "🤌", keywords: "pinched fingers italian"),
        .init(glyph: "🤏", keywords: "pinching hand small tiny"),
        .init(glyph: "✌️", keywords: "victory hand peace two"),
        .init(glyph: "🤞", keywords: "crossed fingers good luck"),
        .init(glyph: "🤟", keywords: "love-you gesture i love you"),
        .init(glyph: "🤘", keywords: "sign of the horns rock metal"),
        .init(glyph: "🤙", keywords: "call me hand shaka"),
        .init(glyph: "👈", keywords: "backhand index pointing left"),
        .init(glyph: "👉", keywords: "backhand index pointing right"),
        .init(glyph: "👆", keywords: "backhand index pointing up"),
        .init(glyph: "🖕", keywords: "middle finger fuck"),
        .init(glyph: "👇", keywords: "backhand index pointing down"),
        .init(glyph: "☝️", keywords: "index pointing up one"),
        .init(glyph: "👍", keywords: "thumbs up good ok yes like approve"),
        .init(glyph: "👎", keywords: "thumbs down bad no dislike disapprove"),
        .init(glyph: "✊", keywords: "raised fist solidarity"),
        .init(glyph: "👊", keywords: "oncoming fist punch bump"),
        .init(glyph: "🤛", keywords: "left-facing fist"),
        .init(glyph: "🤜", keywords: "right-facing fist"),
        .init(glyph: "👏", keywords: "clapping hands applause clap"),
        .init(glyph: "🙌", keywords: "raising hands praise celebrate"),
        .init(glyph: "🫶", keywords: "heart hands love"),
        .init(glyph: "👐", keywords: "open hands"),
        .init(glyph: "🤲", keywords: "palms up together prayer"),
        .init(glyph: "🤝", keywords: "handshake deal agreement"),
        .init(glyph: "🙏", keywords: "folded hands praying please thanks namaste"),

        // Hearts
        .init(glyph: "❤️", keywords: "red heart love"),
        .init(glyph: "🧡", keywords: "orange heart"),
        .init(glyph: "💛", keywords: "yellow heart"),
        .init(glyph: "💚", keywords: "green heart"),
        .init(glyph: "💙", keywords: "blue heart"),
        .init(glyph: "💜", keywords: "purple heart"),
        .init(glyph: "🖤", keywords: "black heart"),
        .init(glyph: "🤍", keywords: "white heart"),
        .init(glyph: "🤎", keywords: "brown heart"),
        .init(glyph: "💔", keywords: "broken heart"),
        .init(glyph: "❤️‍🔥", keywords: "heart on fire passion"),
        .init(glyph: "💕", keywords: "two hearts love"),
        .init(glyph: "💞", keywords: "revolving hearts"),
        .init(glyph: "💓", keywords: "beating heart"),
        .init(glyph: "💗", keywords: "growing heart"),
        .init(glyph: "💖", keywords: "sparkling heart"),
        .init(glyph: "💘", keywords: "heart with arrow cupid"),
        .init(glyph: "💝", keywords: "heart with ribbon gift"),
        .init(glyph: "❣️", keywords: "heart exclamation"),
        .init(glyph: "💌", keywords: "love letter"),

        // Animals — common
        .init(glyph: "🐶", keywords: "dog puppy"),
        .init(glyph: "🐱", keywords: "cat kitten"),
        .init(glyph: "🐭", keywords: "mouse"),
        .init(glyph: "🐹", keywords: "hamster"),
        .init(glyph: "🐰", keywords: "rabbit bunny"),
        .init(glyph: "🦊", keywords: "fox"),
        .init(glyph: "🐻", keywords: "bear"),
        .init(glyph: "🐼", keywords: "panda"),
        .init(glyph: "🐨", keywords: "koala"),
        .init(glyph: "🐯", keywords: "tiger face"),
        .init(glyph: "🦁", keywords: "lion"),
        .init(glyph: "🐮", keywords: "cow face"),
        .init(glyph: "🐷", keywords: "pig face"),
        .init(glyph: "🐸", keywords: "frog"),
        .init(glyph: "🐵", keywords: "monkey face"),
        .init(glyph: "🙈", keywords: "see-no-evil monkey"),
        .init(glyph: "🙉", keywords: "hear-no-evil monkey"),
        .init(glyph: "🙊", keywords: "speak-no-evil monkey"),
        .init(glyph: "🐔", keywords: "chicken"),
        .init(glyph: "🐧", keywords: "penguin"),
        .init(glyph: "🐦", keywords: "bird"),
        .init(glyph: "🐤", keywords: "baby chick"),
        .init(glyph: "🦆", keywords: "duck"),
        .init(glyph: "🦅", keywords: "eagle"),
        .init(glyph: "🦉", keywords: "owl"),
        .init(glyph: "🐺", keywords: "wolf"),
        .init(glyph: "🐗", keywords: "boar pig"),
        .init(glyph: "🐴", keywords: "horse face"),
        .init(glyph: "🦄", keywords: "unicorn"),
        .init(glyph: "🐝", keywords: "honeybee bee"),
        .init(glyph: "🦋", keywords: "butterfly"),
        .init(glyph: "🐌", keywords: "snail"),
        .init(glyph: "🐞", keywords: "lady beetle ladybug"),
        .init(glyph: "🕷️", keywords: "spider"),
        .init(glyph: "🦂", keywords: "scorpion"),
        .init(glyph: "🦀", keywords: "crab"),
        .init(glyph: "🐙", keywords: "octopus"),
        .init(glyph: "🐠", keywords: "tropical fish"),
        .init(glyph: "🐟", keywords: "fish"),
        .init(glyph: "🦈", keywords: "shark"),
        .init(glyph: "🐬", keywords: "dolphin"),
        .init(glyph: "🐳", keywords: "spouting whale"),
        .init(glyph: "🐋", keywords: "whale"),
        .init(glyph: "🐊", keywords: "crocodile"),
        .init(glyph: "🦓", keywords: "zebra"),
        .init(glyph: "🦍", keywords: "gorilla"),
        .init(glyph: "🐘", keywords: "elephant"),
        .init(glyph: "🦏", keywords: "rhinoceros rhino"),
        .init(glyph: "🦒", keywords: "giraffe"),
        .init(glyph: "🦘", keywords: "kangaroo"),
        .init(glyph: "🐃", keywords: "water buffalo"),
        .init(glyph: "🐂", keywords: "ox bull"),
        .init(glyph: "🐄", keywords: "cow"),
        .init(glyph: "🐎", keywords: "horse"),
        .init(glyph: "🐖", keywords: "pig"),
        .init(glyph: "🐑", keywords: "ewe sheep"),
        .init(glyph: "🦙", keywords: "llama"),
        .init(glyph: "🐐", keywords: "goat"),
        .init(glyph: "🦌", keywords: "deer"),
        .init(glyph: "🐕", keywords: "dog"),
        .init(glyph: "🐈", keywords: "cat"),

        // Food — common
        .init(glyph: "🍎", keywords: "red apple fruit"),
        .init(glyph: "🍊", keywords: "tangerine orange fruit"),
        .init(glyph: "🍋", keywords: "lemon fruit"),
        .init(glyph: "🍌", keywords: "banana fruit"),
        .init(glyph: "🍉", keywords: "watermelon fruit"),
        .init(glyph: "🍇", keywords: "grapes fruit"),
        .init(glyph: "🍓", keywords: "strawberry fruit"),
        .init(glyph: "🍒", keywords: "cherries fruit"),
        .init(glyph: "🍑", keywords: "peach fruit"),
        .init(glyph: "🥭", keywords: "mango fruit"),
        .init(glyph: "🍍", keywords: "pineapple fruit"),
        .init(glyph: "🥝", keywords: "kiwi fruit"),
        .init(glyph: "🍅", keywords: "tomato"),
        .init(glyph: "🥑", keywords: "avocado"),
        .init(glyph: "🥦", keywords: "broccoli"),
        .init(glyph: "🥕", keywords: "carrot"),
        .init(glyph: "🌽", keywords: "ear of corn"),
        .init(glyph: "🥔", keywords: "potato"),
        .init(glyph: "🥐", keywords: "croissant"),
        .init(glyph: "🍞", keywords: "bread"),
        .init(glyph: "🥖", keywords: "baguette"),
        .init(glyph: "🥨", keywords: "pretzel"),
        .init(glyph: "🥯", keywords: "bagel"),
        .init(glyph: "🥞", keywords: "pancakes"),
        .init(glyph: "🧀", keywords: "cheese wedge"),
        .init(glyph: "🥚", keywords: "egg"),
        .init(glyph: "🍔", keywords: "hamburger burger"),
        .init(glyph: "🍟", keywords: "french fries fries"),
        .init(glyph: "🌭", keywords: "hot dog"),
        .init(glyph: "🌮", keywords: "taco"),
        .init(glyph: "🌯", keywords: "burrito"),
        .init(glyph: "🍕", keywords: "pizza"),
        .init(glyph: "🍣", keywords: "sushi"),
        .init(glyph: "🍜", keywords: "steaming bowl ramen noodles"),
        .init(glyph: "🍝", keywords: "spaghetti pasta"),
        .init(glyph: "🍰", keywords: "shortcake cake"),
        .init(glyph: "🎂", keywords: "birthday cake"),
        .init(glyph: "🍪", keywords: "cookie"),
        .init(glyph: "🍩", keywords: "doughnut donut"),
        .init(glyph: "🍫", keywords: "chocolate bar"),
        .init(glyph: "🍭", keywords: "lollipop"),
        .init(glyph: "🍿", keywords: "popcorn"),
        .init(glyph: "☕", keywords: "hot beverage coffee tea"),
        .init(glyph: "🍵", keywords: "teacup green tea"),
        .init(glyph: "🍶", keywords: "sake"),
        .init(glyph: "🍷", keywords: "wine glass"),
        .init(glyph: "🍺", keywords: "beer mug"),
        .init(glyph: "🍻", keywords: "clinking beer mugs cheers"),
        .init(glyph: "🥂", keywords: "clinking glasses champagne cheers"),
        .init(glyph: "🍸", keywords: "cocktail glass"),

        // Weather
        .init(glyph: "☀️", keywords: "sun sunny"),
        .init(glyph: "🌤️", keywords: "sun behind small cloud"),
        .init(glyph: "⛅", keywords: "sun behind cloud partly cloudy"),
        .init(glyph: "☁️", keywords: "cloud cloudy"),
        .init(glyph: "🌧️", keywords: "cloud with rain rainy"),
        .init(glyph: "⛈️", keywords: "cloud with lightning and rain storm thunder"),
        .init(glyph: "🌨️", keywords: "cloud with snow snowing"),
        .init(glyph: "❄️", keywords: "snowflake snow cold"),
        .init(glyph: "☃️", keywords: "snowman snow"),
        .init(glyph: "⛄", keywords: "snowman without snow"),
        .init(glyph: "🌪️", keywords: "tornado"),
        .init(glyph: "🌈", keywords: "rainbow"),
        .init(glyph: "☔", keywords: "umbrella with rain drops rain"),
        .init(glyph: "⚡", keywords: "high voltage lightning bolt zap"),
        .init(glyph: "🌊", keywords: "water wave"),
        .init(glyph: "💧", keywords: "droplet water drop"),
        .init(glyph: "💦", keywords: "sweat droplets splash"),

        // Symbols / common
        .init(glyph: "✅", keywords: "check mark green ok done"),
        .init(glyph: "✔️", keywords: "heavy check mark check tick"),
        .init(glyph: "❌", keywords: "cross mark x no wrong"),
        .init(glyph: "⭐", keywords: "star"),
        .init(glyph: "🌟", keywords: "glowing star sparkle"),
        .init(glyph: "✨", keywords: "sparkles shine new"),
        .init(glyph: "🔥", keywords: "fire flame hot lit"),
        .init(glyph: "💥", keywords: "collision boom explosion"),
        .init(glyph: "💯", keywords: "hundred points 100 perfect"),
        .init(glyph: "💢", keywords: "anger symbol"),
        .init(glyph: "💨", keywords: "dashing away wind speed"),
        .init(glyph: "💣", keywords: "bomb explosive"),
        .init(glyph: "💬", keywords: "speech balloon comment"),
        .init(glyph: "💭", keywords: "thought balloon think"),
        .init(glyph: "💤", keywords: "zzz sleeping"),
        .init(glyph: "🎉", keywords: "party popper celebrate congratulations"),
        .init(glyph: "🎊", keywords: "confetti ball celebrate"),
        .init(glyph: "🎈", keywords: "balloon"),
        .init(glyph: "🎁", keywords: "wrapped gift present"),
        .init(glyph: "🎀", keywords: "ribbon bow"),
        .init(glyph: "🎄", keywords: "christmas tree"),
        .init(glyph: "🎃", keywords: "jack-o-lantern halloween pumpkin"),
        .init(glyph: "🎯", keywords: "bullseye target dart"),
        .init(glyph: "🏆", keywords: "trophy winner"),
        .init(glyph: "🥇", keywords: "first place medal gold"),
        .init(glyph: "🥈", keywords: "second place medal silver"),
        .init(glyph: "🥉", keywords: "third place medal bronze"),

        // Time
        .init(glyph: "⏰", keywords: "alarm clock"),
        .init(glyph: "⏱️", keywords: "stopwatch"),
        .init(glyph: "⏳", keywords: "hourglass not done loading"),
        .init(glyph: "⌛", keywords: "hourglass done"),

        // Travel & places — common
        .init(glyph: "🚗", keywords: "car automobile"),
        .init(glyph: "🚙", keywords: "sport utility vehicle suv"),
        .init(glyph: "🚌", keywords: "bus"),
        .init(glyph: "🚕", keywords: "taxi"),
        .init(glyph: "🚓", keywords: "police car"),
        .init(glyph: "🚑", keywords: "ambulance"),
        .init(glyph: "🚒", keywords: "fire engine"),
        .init(glyph: "🚚", keywords: "delivery truck"),
        .init(glyph: "🚲", keywords: "bicycle bike"),
        .init(glyph: "🛴", keywords: "kick scooter"),
        .init(glyph: "🛵", keywords: "motor scooter"),
        .init(glyph: "🏍️", keywords: "motorcycle"),
        .init(glyph: "🚄", keywords: "high-speed train"),
        .init(glyph: "🚅", keywords: "bullet train shinkansen"),
        .init(glyph: "🚆", keywords: "train"),
        .init(glyph: "🚇", keywords: "metro subway"),
        .init(glyph: "✈️", keywords: "airplane plane flight"),
        .init(glyph: "🚀", keywords: "rocket ship launch"),
        .init(glyph: "🛸", keywords: "flying saucer ufo"),
        .init(glyph: "🚁", keywords: "helicopter"),
        .init(glyph: "🛳️", keywords: "passenger ship"),
        .init(glyph: "⛵", keywords: "sailboat"),
        .init(glyph: "🌍", keywords: "globe showing europe africa earth world"),
        .init(glyph: "🌎", keywords: "globe showing americas earth world"),
        .init(glyph: "🌏", keywords: "globe showing asia australia earth world"),
        .init(glyph: "🗾", keywords: "map of japan"),
        .init(glyph: "🏔️", keywords: "snow-capped mountain"),
        .init(glyph: "⛰️", keywords: "mountain"),
        .init(glyph: "🌋", keywords: "volcano"),
        .init(glyph: "🏖️", keywords: "beach with umbrella beach"),
        .init(glyph: "🏝️", keywords: "desert island"),
        .init(glyph: "🏠", keywords: "house home"),
        .init(glyph: "🏢", keywords: "office building"),

        // Objects — common
        .init(glyph: "📱", keywords: "mobile phone iphone"),
        .init(glyph: "💻", keywords: "laptop computer"),
        .init(glyph: "🖥️", keywords: "desktop computer"),
        .init(glyph: "⌨️", keywords: "keyboard"),
        .init(glyph: "🖱️", keywords: "computer mouse"),
        .init(glyph: "💾", keywords: "floppy disk save"),
        .init(glyph: "💿", keywords: "optical disk cd"),
        .init(glyph: "📷", keywords: "camera"),
        .init(glyph: "📸", keywords: "camera with flash"),
        .init(glyph: "📺", keywords: "television tv"),
        .init(glyph: "🎥", keywords: "movie camera film"),
        .init(glyph: "🎬", keywords: "clapper board action"),
        .init(glyph: "🎵", keywords: "musical note music"),
        .init(glyph: "🎶", keywords: "musical notes music"),
        .init(glyph: "🎧", keywords: "headphone headphones"),
        .init(glyph: "🎤", keywords: "microphone mic"),
        .init(glyph: "📞", keywords: "telephone receiver call phone"),
        .init(glyph: "🔋", keywords: "battery"),
        .init(glyph: "💡", keywords: "light bulb idea"),
        .init(glyph: "🔍", keywords: "magnifying glass search find"),
        .init(glyph: "🔒", keywords: "locked lock"),
        .init(glyph: "🔓", keywords: "unlocked unlock"),
        .init(glyph: "🔑", keywords: "key"),
        .init(glyph: "🔨", keywords: "hammer"),
        .init(glyph: "🔧", keywords: "wrench tool"),
        .init(glyph: "⚙️", keywords: "gear settings"),
        .init(glyph: "💰", keywords: "money bag cash"),
        .init(glyph: "💵", keywords: "dollar banknote money"),
        .init(glyph: "💳", keywords: "credit card"),
        .init(glyph: "📝", keywords: "memo note write"),
        .init(glyph: "✏️", keywords: "pencil"),
        .init(glyph: "✒️", keywords: "black nib pen"),
        .init(glyph: "📌", keywords: "pushpin pin"),
        .init(glyph: "📎", keywords: "paperclip"),
        .init(glyph: "📁", keywords: "file folder folder"),
        .init(glyph: "📂", keywords: "open file folder"),
        .init(glyph: "📅", keywords: "calendar date"),
        .init(glyph: "📊", keywords: "bar chart"),
        .init(glyph: "📈", keywords: "chart increasing up trend"),
        .init(glyph: "📉", keywords: "chart decreasing down trend"),
        .init(glyph: "📋", keywords: "clipboard"),
        .init(glyph: "📚", keywords: "books"),
        .init(glyph: "📖", keywords: "open book read"),
        .init(glyph: "✉️", keywords: "envelope email mail"),
        .init(glyph: "📧", keywords: "email e-mail"),
        .init(glyph: "📦", keywords: "package box"),
        .init(glyph: "🎮", keywords: "video game controller game"),
        .init(glyph: "🎲", keywords: "game die dice"),

        // Arrows
        .init(glyph: "⬆️", keywords: "up arrow"),
        .init(glyph: "⬇️", keywords: "down arrow"),
        .init(glyph: "⬅️", keywords: "left arrow"),
        .init(glyph: "➡️", keywords: "right arrow"),
        .init(glyph: "↗️", keywords: "up-right arrow"),
        .init(glyph: "↘️", keywords: "down-right arrow"),
        .init(glyph: "🔄", keywords: "counterclockwise arrows reload refresh sync"),
        .init(glyph: "🔃", keywords: "clockwise vertical arrows"),
    ]
}
